### ISSUE TITLE
issue releases / version control to support dep and other go vendor best practices

### ISSUE THREAD

**Issue by qhenkart** [blacklightcms/recurly#100]
Currently PRs seem to be pushed to master with no tags or connection to releases, combining minor releases, major releases and even those with breaking changes. It makes it difficult to manage this package along with others in a production environment. It is difficult for an outsider to determine which PRs constitute as a non-breaking change or minor release, and which constitute as a major release. Most Go libraries issue releases / versions which works seamlessly with dep and other vendor standards. In this case we have to tie our library to a specific commit and sift through the commit history to determine when to update this library. Please consider utilizing github's release feature https://github.com/blacklightcms/recurly/releases

**Comment by cristiangraz** [comment]
Thanks for the suggestions @qhenkart. The library has evolved from mostly internal use to being used by many others, so I can understand the concern here.

I'm thinking through differentiating between between minor/major releases and trying to avoid breaking changes while also ensuring those who are using the library get the updates they need. Something like a version change could sometimes be small, sometimes be breaking (from Recurly's side), and sometimes we may think something is safe and discover a change from Recurly in some endpoint that impacts someone.

We recently pushed a PR where we converted `int` credit card/CVV types to strings (so they could start with 0) -- a breaking change. Perhaps I'm overthinking it and having frequent major releases would be fine.

I'd love to hear from the you (and others!) on potential versioning strategies, issues you've run into, what's gone smoothly and what's been breaking so I can better manage a release strategy.

**Comment by everdance** [comment]
I just want to share some of our experience here.  we previously pinned to a specific `revision/commit`. This is essentially the same as using version/release control. And as expected, we hadn't had any issue of building passed through staging env but failed somehow later in production env.  Nevertheless, we just recently switched to pinning master branch, the benefits are:
1. keep us in sync with the lib updates which includes potential bugfix from both lib and recurly api
2. fix lib version conflicts across our inner packages.

Given Go is a compiled language env, and that this lib is basically an API delegator. I think release/version control does not offer much advantage.

however, there might be issues under certain conditions. like if the lib has been updated to latest recurly API which will deprecate an old feature your application is still using with your recurly tenant, then you have to pin to old versions. And in this case,  with release/version control would be more convenient.

**Comment by qhenkart** [comment]
without version control there is no clear way to communicate or manage breaking changes, and pinning to master is generally a bad practice if you're running a production app since everyone is prone to making mistakes, including libraries. A bug which would be caught before a major version release might make its way into the master branch. Given that this library has released breaking changes in the past, I think versions would be very appropriate and dep compliant

in our case, we run a large enterprise app and we can't always devote engineering resources to updating details that change with a library. We stopped updating this library out of fear of more breaking changes a long time ago. I'm looking forward to version control at some point

**Comment by cristiangraz** [comment]
I released `v0.1` which is the latest version of master.

Once #118 is ready I'll tag release `v1.0` and then keep up with it after that. Thanks for the feedback!
