### ISSUE TITLE
Wrong types in Credit Card Info

### ISSUE THREAD

**Issue by bagbee** [blacklightcms/recurly#101]
Why do you use type _int_ for fields _Number_ and _VerificationValue_? 
[Credit card number and CVV can start from zero](https://stackoverflow.com/questions/7164858/can-credit-card-numbers-contain-leading-zeros/7164969) and this will be a problem for the current implementation.

I think for these fields need to use the type _string_, as written in the [recurly documentation](https://dev.recurly.com/docs/create-an-accounts-billing-info-credit-card)

**Comment by cristiangraz** [comment]
@bagbee Yes that's correct. This was a mistake in the initial implementation -- we've been [slowly](https://github.com/blacklightcms/recurly/pull/81) [updating these](https://github.com/blacklightcms/recurly/pull/38), although the ones you've cited were clearly missed.

Please open a PR with the changes.

**Comment by bagbee** [comment]
ok, thanks
