### ISSUE TITLE
Transaction errors

### ISSUE THREAD

**Issue by bagbee** [blacklightcms/recurly#102]
The documentation says:

> In addition to the Errors property in the recurly.Response, response also contains a TransactionError field for Transaction Errors.
Be sure to check resp.TransactionError for any API calls that may return a transaction error for additional info.

And i'm confused because  [response struct](https://github.com/blacklightcms/recurly/blob/master/responses.go#L12) does not have _TransactionError_ propery, only private _transaction_

**Comment by cristiangraz** [comment]
@bagbee It looks like when this was [updated](https://github.com/blacklightcms/recurly/pull/35), we did not update the documentation.

Every response that returns a [`Transaction`](https://godoc.org/github.com/blacklightcms/recurly#Transaction) has a [`TransactionError`](https://godoc.org/github.com/blacklightcms/recurly#TransactionError), if available, via the [`Transaction`](https://godoc.org/github.com/blacklightcms/recurly#Transaction) struct. Any transaction errors can be checked there.

If you are looking for this error in a certain API call and don't see it, drop a comment here. I'll use this issue to track the documentation update needed. Thanks for catching!

**Comment by bagbee** [comment]
got it, thanks

**Comment by cfortuner** [comment]
Can we reopen this as an issue? 

Right now in _client.go_ , when the function [do](https://github.com/blacklightcms/recurly/blob/a98df3111870af50a515b0924d064286409034f6/client.go#L131) receives a response of 422 StatusUnprocessableEntity from[ Recurly's Create Purchase API](https://dev.recurly.com/docs/create-purchase), there is no way to get the Transaction or Transaction Error. 

```
if reponse.IsError() {
  if response.StatusCode == http.StatusUnprocessableEntity {
	var ve struct {
		Errors      []Error      `xml:"error"`
		Transaction *Transaction `xml:"transaction,omitempty"`

		// At least one 422 response can return a single error instead of an array.
		// https://dev.recurly.com/docs/welcome#section-422-unprocessable-entity-responses
		Symbol      string `xml:"symbol"`
		Description string `xml:"description"`
	}

	...

	// If the response object includes a TransactionError, set the
	// transaction field on the response object and the TransactionError field.
	if ve.Transaction != nil {
		response.transaction = ve.Transaction
	}
  } 
 ...

  return response, nil
}
```


This is bad as now the user has no way of accessing the helpful Recurly [Transaction Errors](https://dev.recurly.com/page/transaction-errors) 
 
Can we please export Transaction again in the response????

If I am missing something and there IS a way to get the Transaction Error details please let me know!
