### ISSUE TITLE
Unable to access Transaction Errors in Response

### ISSUE THREAD

**Issue by cfortuner** [blacklightcms/recurly#110]
Right now in client.go, when the function: do receives a response of 422 StatusUnprocessableEntity from Recurly's Create Purchase API, there is no way to get the Transaction or Transaction Error.

if reponse.IsError() {
  if response.StatusCode == http.StatusUnprocessableEntity {
	var ve struct {
		Errors      []Error      `xml:"error"`
		Transaction *Transaction `xml:"transaction,omitempty"`

		// At least one 422 response can return a single error instead of an array.
		// https://dev.recurly.com/docs/welcome#section-422-unprocessable-entity-responses
		Symbol      string `xml:"symbol"`
		Description string `xml:"description"`
	}

	...

	// If the response object includes a TransactionError, set the
	// transaction field on the response object and the TransactionError field.
	if ve.Transaction != nil {
		response.transaction = ve.Transaction
	}
  } 
 ...

  return response, nil
}
This is bad as now the user has no way of accessing the helpful Recurly Transaction Errors

Can we please export Transaction again in the response????

If I am missing something and there IS a way to get the Transaction Error details please let me know!

**Comment by cristiangraz** [comment]
Hey @cfortuner. I saw your PR yesterday, I'm digging into some old history and looking through the history to see why we initially made the change to unexported. I think your PR will be safe to merge, but I'll reply to the PR later today.

**Comment by cfortuner** [comment]
Thanks Christian!

**Comment by cfortuner** [comment]
Hey! Just wanted to check in to see if you were able to review the history for this?

**Comment by cristiangraz** [comment]
Hi @cfortuner,

Yes it was this PR: https://github.com/blacklightcms/recurly/pull/35

We moved it to an unexported type because we mapped it internally everywhere we thought it was returned. Your case is different from the others, so having the transaction be exported for that use case (and likely others like it) makes sense.

Thanks for contributing!
