### ISSUE TITLE
Support for handling cursor externally

### ISSUE THREAD

**Issue by kmikiy** [blacklightcms/recurly#120]
You've done a great job with v1.0.0

I was wondering if you could add support for handling the `cursor` for paginated records externally?

https://github.com/blacklightcms/recurly/blob/b954acff45d59241062436dc0203ae5b58071753/pager.go#L341

We use pagination on our frontend for e.g. retrieving invoices. Currently, we use the cursor for this, but with v1.0.0 I can no longer access the cursor.

**Comment by cristiangraz** [comment]
Hi @kmikiy,

Thanks for the note. This is a great idea, and one I hadn't thought of initially. I have something prototyped locally that should let you 1) access the prev/next cursors and 2) set a starting cursor without introducing any breaking changes.

I'll push up a PR shortly after I write some tests and try it out!

**Comment by cristiangraz** [comment]
@kmikiy See https://github.com/blacklightcms/recurly/pull/121. Let me know if this covers your use case and/or if you have any suggestions.

**Comment by kmikiy** [comment]
I just tested it. It works like a charm 👌🏻
