### ISSUE TITLE
tagging releases?

### ISSUE THREAD

**Issue by bhb603** [blacklightcms/recurly#126]
Hi there, 

We recently upgraded to v1.0.0 (thanks for the migration guide btw!).

Just wondering if you're planning to continue tagging stable releases with semver? E.g. I see [this PR](https://github.com/blacklightcms/recurly/pull/125) merged, which upgrades to recurly API v2.21, but there is no accompanying tag/release in this repo.

Will there be, for example a v1.1.0?
Or should we assume everything in `master` is "stable", and I can reference the commit hash rather than a version in `Gopkg.toml` (we also use dep)?

**Comment by cristiangraz** [comment]
Hi @bhb603, assuming `master` is stable is a reasonable assumption for this library. I will continue tagging releases however, I just hadn't gotten around to tagging those two. I'll prepare a release today or tomorrow with those though!
