### ISSUE TITLE
Add a user agent for tracking purposes

### ISSUE THREAD

**Issue by bhelx** [blacklightcms/recurly#41]
At Recurly, we use a specific format for the user agent which allows us to do analytics on what  libraries, versions, and environments our customers are using. This helps us with the feedback process of developing or making changes to our clients. I'd love to help support this library and I think the first step is getting this agent in and tracking who is using the library and how.

The format is roughly:

```
<company-identifier>/<library-version>; <environment-description>
```

This is what the code to generate this looks like in ruby:

```ruby
# @return [String]
def user_agent
  "Recurly/#{Version}; #{RUBY_DESCRIPTION}"
end
```

Which would result in a string like this:

```ruby
"Recurly/2.10.1; ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]"
```

So perhaps your string could use the company identifier `BlackLight`. I leave it to you to decide which environment properties would be useful to track.

**Comment by cristiangraz** [comment]
Thanks @bhelx. I added a `help wanted` label in case someone in the community is able to take this. Otherwise we will try to get to it this month if possible.

**Comment by bhelx** [comment]
Thanks @cristiangraz

I'm not a Go developer but might pick it up next week if no one else does.

**Comment by bhelx** [comment]
Thanks @cristiangraz !
