### ISSUE TITLE
Add a support for new Recurly feature: custom-fields

### ISSUE THREAD

**Issue by yauvansuba** [blacklightcms/recurly#66]
Recurly has a new feature. Can we add a support for it? 

Here is a documentation on this feature.
https://docs.recurly.com/v1.0/docs/custom-fields

**Comment by katenicoletti** [comment]
Hi @yauvansuba, this is not currently on our roadmap but feel free to submit a PR. Please see the [contribution guidelines](https://github.com/blacklightcms/recurly/blob/master/CONTRIBUTING.md) for more information!

**Comment by yauvansuba** [comment]
Sounds good. I created PR: https://github.com/blacklightcms/recurly/pull/67

**Comment by katenicoletti** [comment]
PR #67 has been merged.
