### ISSUE TITLE
Transaction struct missing original_transaction?

### ISSUE THREAD

**Issue by michael-luo** [blacklightcms/recurly#83]
Transaction: https://godoc.org/github.com/blacklightcms/recurly#Transaction
 
In the Ruby library we would be able to get the original transaction by calling transaction.original_transaction, is there an easy way to get it in this Go library too?

**Comment by michael-luo** [comment]
I think I can currently get around this by calling transaction.invoice.original_invoice.transactions[0] to get the original transaction of the transaction

**Comment by cristiangraz** [comment]
@michael-luo Are you looking for the original transaction for an invoice, for an account?

The invoices get method sorts all of the transactions:
https://github.com/blacklightcms/recurly/blob/489a558f74b65f8d49bb4870692ca9a63d9b0107/invoices_service.go#L72

It's sorted by the transaction's created date in ascending order. You can check out the sort logic we use at the link above here:
https://github.com/blacklightcms/recurly/blob/master/transactions.go#L170-L184

So if you are retrieving an invoice, the first transaction in the list will be the original based on the created timestamp.

**Comment by michael-luo** [comment]
My original use case was to try to get the original payment txn for a refund txn. Sounds like getting the first txn in the list works, thanks.
